
#' LeafletJS Map
#'
#' Builds an interactive map of locations for any species
#' @param ee_obj A ecoengine object of type \code{observations} as generated by \code{\link{ee_observations}}
#' @param  dest Location where the html file and geojson file should be stored. Default is the temp directory
#' @param  title Title of the map.
#' @param  overwrite Default is \code{TRUE}. Set to \code{FALSE} to avoid overwriting previously created html files. NOT YET FUNCTIONAL. Waiting on leafletR update.
#' @param  browser Maps currently don't render in Google Chrome. The problem is the security restriction of Chrome. Local file access is denied, even in the same directory. Thus the JavaScript in the HTML file cannot load the data from the GeoJSONfile. It only works if the files are uploaded on a server. To get around this, you can specify a different browser to use just for this function. You can also set one for R in your options. (e.g. \code{options(browser = "/Applications/Firefox.app/Contents/MacOS/firefox") }). 
#' @export
#' @keywords map
#' @import leafletR
#' @importFrom RColorBrewer brewer.pal
#' @examples \dontrun{
#' lynx_data <- ee_observations(genus = "Lynx", georeferenced = TRUE, page = "all", quiet = TRUE)
#' ee_map(lynx_data, title = "Lynx distribution map")
#' # Now let's map out foxes
#' vulpes <- ee_observations(genus = "vulpes", georeferenced = TRUE, quiet = TRUE)
#' ee_map(vulpes, title = "Fox distributions")
#' # Google Chrome currently does not render the maps because of security restrictions
#' # If Firefox or Safari aren't your default browser, you can specify that in your path.
#' # options(browser = "/Applications/Firefox.app/Contents/MacOS/firefox") 
#' # or passing it inline
#' # ee_map(vulpes, title = "Fox distributions", browser = "/Applications/Firefox.app/Contents/MacOS/firefox")
#' # Obviously your path will vary depending on your OS.
#'}
ee_map <- function(ee_obj, dest = tempdir(), title = "Ecoengine species map", overwrite = TRUE, browser = getOption("browser")) {
	assert_that(ee_obj$type == "observations")
	dest <- ifelse(is.null(dest), tempdir(), dest)
	species_data <- ee_obj$data
	ee_geo <- toGeoJSON(data = species_data, name = "temp", dest = dest, lat.lon=c(12, 11))	
	num_species <- length(unique(species_data$scientific_name))
	cols <- c("#8D5C00", "#2F5CD7","#E91974", "#3CB619","#7EAFCC",
"#4F2755","#F5450E","#264C44","#3EA262","#FA43C9","#6E8604","#631D0E","#EE8099","#E5B25A",
"#0C3D8A","#9E4CD3","#195C7B","#9F8450","#7A0666","#BBA3C5","#F064B4","#108223","#553502",
"#17ADE7","#83C445","#C52817","#626302","#9F9215","#6CCD78","#BF3704")
	pal <- cols[1:num_species]
	sty <- styleCat(prop = "scientific_name", val = unique(species_data$scientific_name), style.val = pal, fill.alpha = 1, alpha = 1, rad = 4)
	map <- leaflet(ee_geo, base.map="tls", style = sty, popup = "scientific_name", dest = dest, title = title)
	message("Map will not render on Google Chrome due to the browser's security restrictions. Please use Firefox/Safari until this issue is resolved. \n")
	browseURL(map)
}






