
#' LeafletJS Map
#'
#' Builds an interactive map of locations for any species
#' @param ee_obj A ecoengine object of type \code{observations} as generated by \code{\link{ee_observations}}
#' @param  dest Location where the html file and geojson file should be stored. Default is the temp directory
#' @param  title Title of the map.
#' @export
#' @keywords map
#' @import leafletR
#' @importFrom RColorBrewer brewer.pal
#' @examples \dontrun{
#' lynx_data <- ee_observations(genus = "Lynx", georeferenced = TRUE, page = "all", quiet = TRUE)
#' ee_map(lynx_data, title = "Lynx distribution map")
#' # Now let's map out foxes
#' vulpes <- ee_observations(genus = "vulpes", georeferenced = TRUE, quiet = TRUE)
#' ee_map(vulpes, title = "Fox distributions")
#'}
ee_map <- function(ee_obj, dest = tempdir(), title = "Ecoengine species map") {
	assert_that(ee_obj$type == "observations")
	dest <- ifelse(is.null(dest), tempdir(), dest)
	species_data <- ee_obj$data
	ee_geo <- toGeoJSON(data = species_data, name = "temp", dest = dest, lat.lon=c(12, 11))	
	num_species <- length(unique(species_data$scientific_name))
	if(num_species > 12) {
		stop("Can't create a color scale for more than 12 species", call. = FALSE)
	}
	pal <- brewer.pal(num_species,  "Set3")
	sty <- styleCat(prop = "scientific_name", val = unique(species_data$scientific_name), style.val = pal, fill.alpha = 1, alpha = 1, rad = 6)
	map <- leaflet(ee_geo, base.map="tls", style = sty, popup = "scientific_name", dest = dest, title = title)
	message("Map will not render on Google Chrome due to the browser's security restrictions. Please use Firefox/Safari until this issue is resolved \n")
	browseURL(map)
}






